name: Build Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java:
          - '8'
          - '11'
          - '17'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            java: '1.8'
          - os: macos-latest
            java: '17'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing assemble
          unset GEM_PATH GEM_HOME JRUBY_OPTS
          ./gradlew -S -Pskip.signing check
      - name: Upstream Build
        if: matrix.os == 'ubuntu-latest' && matrix.java == '1.8'
        run: |
          unset GEM_PATH GEM_HOME JRUBY_OPTS
          ./test-asciidoctor-upstream.sh
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java:
          - '11'
          - '17'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Assemble
        shell: cmd
        run: |
          gradlew.bat -i assemble
      - name: Check
        shell: cmd
        run: |
          gradlew.bat -i -S check
